
### POST Crear producto
POST http://localhost:8080/api/product
Content-Type: application/json

{
  "name": "Pan y picos",
  "price": 1,
  "details": "Servicio de mesa"
}

### GET obtener todos los productos
GET http://localhost:8080/api/product

### GET obtener producto id 1
GET http://localhost:8080/api/product/1


### PUT Modificar producto
PUT http://localhost:8080/api/product/1
Content-Type: application/json

{
  "name": "Pan y picos",
  "price": -13,
  "details": "Servicio de mesa por persona"
}

### DELETE borrar producto id 1
DELETE http://localhost:8080/api/product/1