### POST Crear producto
POST http://localhost:8080/api/product
Content-Type: application/json

{
  "nombre": "Pan y picos",
  "precio": 1
}

### GET obtener todos los productos
GET http://localhost:8080/api/product

### GET obtener producto id 1
GET http://localhost:8080/api/product/1